#!/bin/sh
# top level export PPP_IFACE PPP_TTY PPP_SPEED PPP_LOCAL PPP_REMOTE PPP_IPPARAM

. /etc/cdb.sh
. /etc/rdb.sh

config_set wanif_state ${STATE_DISCONNECTED}

# original position : /package/ppp/files/etc/ppp/ip-down.d
#/etc/init.d/wan_serv down
mtc_cli wanipdown
